# Site settings
title: Simple Sensationz
email: simplesensationz@offblockfilms.com
description: ""
baseurl: ""
url: "http://simplesensationz.offblockfilms.com/"

# Build settings
markdown: kramdown
permalink: products/:title